name: Deployment
on:
  push:
    branches:
      - master
env:
  MONGODB_DB_NAME: cluster0
  PORT: ${{ secrets.username }}
jobs:
  deploy:
    environment: testing
    env:
     PORTS: ${{ secrets.username }}
    runs-on: windows-latest
    steps:
      - name: testing
        id: test
        run: |
         rcho
      - name: Output information
        if: failure() && steps.test.outputs == 'failure'
        run: |        
          write-host "this is the port number : $env:PORT"
          write-host "another way to print he port number : ${{ env.PORTS}}"
