name: matrix strategy
on:
  push
jobs:
  build:
    strategy:
      matrix:
        version: [14,16,12]
        runner: [windows-latest,ubuntu-latest]
    runs-on: ${{ matrix.runner}} 
    steps:
      - name: install JS
        uses: action/setup-node@v4
        with:
          node-version: ${{matrix.version}}
