name: main
on:
    workflow_dispatch:
    push:
jobs:
    check:
        runs-on: windows-latest
        steps:
            - name: get-code
              uses: actions/checkout@v4
            - name: just print
              run: write-host "printing"

    calling:
        needs: check
        uses: ./.github/workflows/reusable.yml
        with:
            testinput1: someone
        secrets:
            name: ${{ secrets.USERNAME}}
    
    printing:
        needs: calling
        runs-on: ubuntu-latest
        steps:
            - name: print output
              run: echo" ${{ needs.calling.outputs.OP}} "