name: reusable-workflow
on:
  workflow_call:
    inputs:
      testinput1:
        required: true
        description: just to test
        type: string
    secrets:
      name:
        required: true
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: just print
        run: |
          echo "test by ${{inputs.testinput1 }}  by using the secredt ${{ secrets.name}}"
          echo "test by ${{inputs.testinput1 }} for second time to find about secret working "