name: reusable-workflow
on:
  workflow_call:
    inputs:
      testinput1:
        required: true
        description: just to test
        type: string
        default: print anything
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: just print
        run: echo " test by ${{inputs.testinput1 }}"