name: reusable-workflow
on:
  workflow_call:
    inputs:
      testinput1:
        required: true
        description: just to test
        type: string
    secrets:
      name:
        required: true
    outputs:
      OP:
        description: nothing important just output 
        value: ${{ jobs.print.outputs.outcome}}
jobs:
  print:
    outputs:
      outcome: ${{ steps.demo.outputs.firstop}}
    runs-on: ubuntu-latest
    steps:
      - name: just print
        run: |
          echo "test by ${{inputs.testinput1 }}  by using the secredt ${{ secrets.name}}"
          echo "test by ${{inputs.testinput1 }} for second time to find about secret working "
      - name: produce output
        id: demo
        run: echo "firstop=success" >> $GITHUB_OUTPUT